name = "Ships and Skies"
author = "Rowantale"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe66a9ba16e29777996fb11cc1bcaf537e5b5b38af68bbe23142f2b558ead5ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.225"
unsup = "1.2.3"
