name = "Ships and Skies"
author = "Rowantale"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "616ce3786ec28347a4a7d6f2c16df272d5769aa8c9d138bc9ad1ecb487d07813"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.225"
unsup = "1.2.3"
