[flavor_groups.shaders]
name = "Shaders"
description = "Would you like shaders? They may not work perfectly with new mods like Aeronautics!"
side = "client"
[[flavor_groups.shaders.choices]]
id = "yesshaders"
name = "Shaders Please!"
description = "Installs Iris - Sodium is in by default for (usually) better performance!"
[[flavor_groups.shaders.choices]]
id = "noshaders"
name = "No Shaders"
description = "Iris will not be installed."

[flavor_groups.particles]
name = "Extra Particles"
description = "Subtle Effects adds some particles and sound effects, but may slightly affect performance and may be considered visually busy by some."
side = "client"
[[flavor_groups.particles.choices]]
id = "shinies"
name = "Shinies"
description = "Adds Subtle Effects - if you want to only have one kind of fireflies, turn them off in Particular's config."
[[flavor_groups.particles.choices]]
id = "bland"
name = "No Shinies"
description = "Subtle Effects will not be installed, but there's plenty to look at without it!"

[flavor_groups.distance]
name = "Horizons"
description = "Install Distant Horizons for further render distance? Volatile for performance, can be better or worse. Tested, but not guaranteed."
side = "client"
[[flavor_groups.distance.choices]]
id = "farsight"
name = "Distant"
description = "Adds Distant Horizons - preconfigured to work with Better Clouds!"
[[flavor_groups.distance.choices]]
id = "nearsight"
name = "Normal"
description = "Your horizons will end at the usual distance."

[metafile.iris]
flavors = ["yesshaders"]
[metafile.subtle-effects]
flavors = ["shinies"]
[metafile.distanthorizons]
flavors = ["farsight"]